services:
  gui:
    image: starversserver
    container_name: starvers-gui_prod
    ports:
      - 5001:5000
    volumes:
      - ../app/gui:/code/app/gui
      - ../app/AppConfig.py:/code/app/AppConfig.py
      - ../app/LoggingConfig.py:/code/app/LoggingConfig.py
      - ${data_storage}/evaluation:/data/evaluation
      - ${data_storage}/logs:/data/logs
    depends_on:
      db:
        condition: service_started
      rdfstore:
        condition: service_started
    env_file: "./prod.env"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - starvers_prod_net
    entrypoint: ["python", "app/run_gui.py"]

  starversserver:
    image: starversserver # should be changed to ghcr.io/martinmitteregger/starversserver:main
    container_name: starvers-server_prod
    restart: always
    ports:
      - 8000:8000 # default univcorn
    env_file: "./prod.env"
    volumes:
      - ${data_storage}/evaluation:/data/evaluation
      - ${data_storage}/logs:/data/logs
      - ${data_storage}/graphdb-data/graphdb-import:/graphdb-import
    depends_on:
      db:
        condition: service_started
      rdfstore:
        condition: service_started
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - starvers_prod_net
    entrypoint: ["uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]

  db:
    image: postgres:17
    container_name: starvers-db_prod
    restart: always
    env_file: "./prod.env"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: starvers_db
    ports:
      - 5433:5432
    volumes:
      - ${data_storage}/postgresql/data:/var/lib/postgresql/data
    networks:
      - starvers_prod_net

  rdfstore:
    image: ontotext/graphdb:10.5.0
    container_name: starvers-rdfstore_prod
    restart: always
    env_file: "./prod.env"
    environment: 
      GDB_JAVA_OPTS: >-
        -Xmx32g -Xms32g
        -Dgraphdb.home=/opt/graphdb/home
        -Dgraphdb.workbench.importDirectory=/opt/graphdb/home/graphdb-import
        -Dgraphdb.workbench.cors.enable=true
        -Denable-context-index=true
        -Dentity-pool-implementation=transactional
        -Dhealth.max.query.time.seconds=60
        -Dgraphdb.append.request.id.headers=true
        -Dreuse.vars.in.subselects=true
        -Dgraphdb.health.minimal.free.storage.enabled=false
        -Dgraphdb.health.minimal.free.storage.asyncCheck=false
        -Dgraphdb.connector.port=7200
    ports: 
      - 7400:7200
    volumes:
      - ${data_storage}/graphdb-data:/opt/graphdb/home
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - starvers_prod_net

  rdfstore_bi:
    image: ontotext/graphdb:10.5.0
    container_name: starvers-rdfstore_bi
    restart: always
    env_file: "./prod.env"
    environment: 
      GDB_JAVA_OPTS: >-
        -Xmx40g -Xms40g
        -Dgraphdb.home=/opt/graphdb/home
        -Dgraphdb.workbench.importDirectory=/opt/graphdb/home/graphdb-import
        -Dgraphdb.workbench.cors.enable=true
        -Denable-context-index=true
        -Dentity-pool-implementation=transactional
        -Dhealth.max.query.time.seconds=60
        -Dgraphdb.append.request.id.headers=true
        -Dgraphdb.auth=false
        -Dreuse.vars.in.subselects=true
        -Dgraphdb.health.minimal.free.storage.enabled=false
        -Dgraphdb.health.minimal.free.storage.asyncCheck=false
        -Dgraphdb.connector.port=7200
    ports: 
      - 7500:7200
    volumes:
      - /mnt/data/starversserver_bi/graphdb-data:/opt/graphdb/home
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - starvers_bi_net

  rdstore_bi_recovery:
    image: starvers_eval:latest
    container_name: starvers-rdfstore_bi_recovery
    restart: "no"
    env_file: "./prod.env"
    environment: 
      GDB_JAVA_OPTS: >-
        -Xmx40g -Xms40g
        -Dgraphdb.home=/opt/graphdb/home
        -Dgraphdb.workbench.importDirectory=/opt/graphdb/home/graphdb-import
        -Dgraphdb.workbench.cors.enable=true
        -Denable-context-index=true
        -Dentity-pool-implementation=transactional
        -Dhealth.max.query.time.seconds=60
        -Dgraphdb.append.request.id.headers=true
        -Dgraphdb.auth=false
        -Dreuse.vars.in.subselects=true
        -Dgraphdb.health.minimal.free.storage.enabled=false
        -Dgraphdb.health.minimal.free.storage.asyncCheck=false
        -Dgraphdb.connector.port=7200
      JAVA_HOME: /opt/java/java11/openjdk
      PATH: /opt/java/java11/openjdk/bin:$PATH
    volumes:
      - /mnt/data/starversserver_bi/graphdb-data:/opt/graphdb/home
      - /mnt/data/starversserver_bi/recovery-output:/opt/graphdb/recovery-output
      - ${home}/starvers/src/starversserver/app/utils/graphdb_recovery.py:/opt/graphdb/run_storage_recovery.py:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - starvers_bi_net
    entrypoint: >
      sh -c "
        echo 'Starting GraphDB recovery wrapper...';
        python3 /opt/graphdb/run_storage_recovery.py;
        echo 'Recovery script finished';
        tail -f /dev/null
      "



  nginx:
    image: openresty/openresty:alpine
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx_default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/html:/var/www/certbot
      - ./nginx/logs:/var/log/nginx
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    networks:
      - starvers_prod_net
      - starvers_bi_net
    depends_on:
      - rdfstore
      - rdfstore_bi
      - db
      - gui

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./nginx/html:/var/www/certbot
      - /${data_storage}/logs/letsencrypt:/var/log/letsencrypt
    networks:
      - starvers_prod_net
      - starvers_bi_net
    entrypoint: >
      sh -c "certbot certonly --non-interactive --webroot
      --webroot-path=/var/www/certbot
      --email filip.kovacevic@tuwien.ac.at
      --agree-tos
      --no-eff-email
      -d starvers.ec.tuwien.ac.at"

  # Reload nginx after renewal
  certbot-renew:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./nginx/html:/var/www/certbot
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - starvers_prod_net
      - starvers_bi_net
    entrypoint: >
      sh -c "certbot renew --webroot --webroot-path=/var/www/certbot"

volumes:
  certbot-etc:
  certbot-var:

networks:
  starvers_prod_net:
    driver: bridge
  starvers_bi_net:
    driver: bridge
