services:
  gui:
    image: starversserver 
    container_name: starvers-gui_dev
    ports:
      - 5000:5000
    volumes:
      - ../app/gui:/code/app/gui
      - ${data_storage}/evaluation:/data/evaluation
      - ${data_storage}/logs:/data/logs
    depends_on:
      db:
        condition: service_started
      rdfstore:
        condition: service_started
    env_file: "./dev.env"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    entrypoint: ["python", "app/run_gui.py"]

  starversserver:
    image: starversserver 
    container_name: starvers-server_dev
    restart: always
    ports:
      - 81:80
    env_file: "./dev.env"
    volumes:
      - ${data_storage}/evaluation:/data/evaluation
      - ${data_storage}/logs:/data/logs
      - ${data_storage}/graphdb-data/graphdb-import:/graphdb-import
    depends_on:
      db:
        condition: service_started
      rdfstore:
        condition: service_started
    entrypoint: ["uvicorn", "app.main:app", "--reload"]
  
  db:
    image: postgres
    container_name: starvers-db_dev
    restart: always
    env_file: "./dev.env"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: starvers_db
    ports:
      - 5432:5432
    volumes:
      - ${data_storage}/postgresql/data:/var/lib/postgresql/data

  rdfstore:
    image: ontotext/graphdb:10.5.0
    container_name: starvers-rdfstore_dev
    restart: always
    env_file: "./dev.env"
    environment: 
      GDB_JAVA_OPTS: >-
        -Xmx32g -Xms32g
        -Dgraphdb.home=/opt/graphdb/home
        -Dgraphdb.workbench.importDirectory=/opt/graphdb/home/graphdb-import
        -Dgraphdb.workbench.cors.enable=true
        -Denable-context-index=true
        -Dentity-pool-implementation=transactional
        -Dhealth.max.query.time.seconds=60
        -Dgraphdb.append.request.id.headers=true
        -Dreuse.vars.in.subselects=true
        -Dgraphdb.health.minimal.free.storage.enabled=false
        -Dgraphdb.health.minimal.free.storage.asyncCheck=false
    ports: 
      - 7200:7200
    volumes:
      - ${data_storage}/graphdb-data:/opt/graphdb/home
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  validate:
    image: starversserver
    container_name: starvers-validate_dev
    env_file: "./dev.env"
    volumes:
      -  ${data_storage}/evaluation:/data/evaluation
      -  ${data_storage}/logs:/data/logs
    entrypoint: ["java", "-jar", "/code/app/utils/rdfvalidator-1.0-jar-with-dependencies.jar"]

  test_download:
    image: starversserver_dev
    container_name: starvers-download_dev
    env_file: "./dev.env"
    ports:
      - 82:80
    volumes:
      - ${data_storage}/evaluation:/data/evaluation
      - ${data_storage}/logs:/data/logs
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - starvers_dev_net
    entrypoint: ["python", "/code/app/utils/HelperService.py", "obtain_nt",
     "https://vocab.linkeddata.es/datosabiertos/def/medio-ambiente/calidad-aire/ontology.nt", "/data/evaluation/si/si.raw.nt"]
    #entrypoint: ["sh"]
    #tty: true
    #stdin_open: true
networks:
  starvers_dev_net:
    driver: bridge
